#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "quality" / "stack_manifest.json"


def check_path(rel: str) -> dict:
    p = ROOT / rel
    exists = p.exists()
    detail = "missing"
    if exists:
        if p.is_dir():
            try:
                count = sum(1 for _ in p.iterdir())
            except Exception:
                count = -1
            detail = f"directory:{count} entries"
        else:
            detail = f"file:{p.stat().st_size} bytes"
    return {"path": rel, "exists": exists, "detail": detail}


def main() -> int:
    manifest = json.loads(MANIFEST.read_text())
    report = {"release_rule": manifest["release_rule"], "checks": [], "summary": {}}
    blocked = 0
    for item in manifest["critical"]:
        evidence = [check_path(x) for x in item.get("evidence", [])]
        present = bool(evidence) and all(x["exists"] for x in evidence)
        # Presence is necessary but not sufficient. Runtime proof checks stay UNVERIFIED
        # until evidence generated by live tests exists.
        requires_live = item["id"] in {
            "owner_voice","approval_bridge","steward_return","runtime","chatdev",
            "easy_jobs","restart_recovery","secrets","first_dollar"
        }
        status = "PRESENT_UNVERIFIED" if present and requires_live else ("PRESENT" if present else "BLOCKED")
        if status == "BLOCKED":
            blocked += 1
        report["checks"].append({"id": item["id"], "label": item["label"], "status": status, "evidence": evidence})
    report["summary"] = {
        "blocked": blocked,
        "critical_total": len(report["checks"]),
        "complete": all(x["status"] == "PASS" for x in report["checks"]),
        "note": "PRESENT is not PASS. Live proof is required before completion."
    }
    print(json.dumps(report, indent=2))
    return 1 if blocked else 0

if __name__ == "__main__":
    raise SystemExit(main())
